### ISSUE TITLE
Suggestion: Arcade Database as source

### ISSUE THREAD

**Issue by HVR88** [Fr75s/bigscraperqt#1]
I made the suggestion earlier in the Pegasus discord as I'd forgotten there was a github for this project. :)

For Arcade, it would be very nice to support the database here: http://adb.arcadeitalia.net/

Skyscraper, which is included with Retropie as optional, supports this source (and others) using priority settings. Its codebase is essentially frozen, but would make a good resource for this project with a GUI. Having LB as a source with the others already supported (like ScreenScraper.fr) would be amazing

**Comment by Fr75s** [comment]
Arcade Database has been added as a scraping source in 7dcc137 and is now in bigscraper-qt v1.3.0.

The menu to change the scraper used is located in the options page. There, you are able to pick between LaunchBox and Arcade Database.

Thank you for your suggestion.
