### ISSUE TITLE
[feature request] Scrape lutris games

### ISSUE THREAD

**Issue by FrenchGithubUser** [Fr75s/bigscraperqt#2]
Hi, thanks for this amazing tool you made !

I was wondering if it was a plan to scrape games that are imported in lutris ? This differs from PC games as it allows to tweak launching options in lutris while still launching them from pegasus (or any other frontend).

**Comment by Fr75s** [comment]
Hello,

While this sounds like an interesting idea, I am unfamiliar with Lutris, so I would like to know what the benefit might be from scraping Lutris for games with this tool vs. using Pegasus's built in Lutris functionality. I feel like my implementation may be worse as the Lutris data would need to be rescraped each time it changes vs. Pegasus scanning it every time the game list is reloaded, meaning data from my app would be more outdated.

If there is a benefit to adding Lutris to bigscraper-qt vs using Lutris in Pegasus (I don't think EmulationStation has Lutris support, and that's the only other export option there is right now), then feel free to elaborate here or on [the discord server.](https://discord.gg/DUAFMgrhAY)

**Comment by FrenchGithubUser** [comment]
AFAIK, lutris only scrapes a banner and a logo. So it might be useful to scrape all the other assets (video, background, poster etc.) + sometimes lutris doesn't find anything. Pegasus would still get the gamelist from lutris, but the assets from the scraped ones. As it is explained in the [docs](https://pegasus-frontend.org/docs/user-guide/faq/#customizing-steam-games) for steam, it works in the same way for lutris : `You can create a metadata file that lists the game you want to customize, and the game file has to be lutris:IDENTIFIER, where the game's identifier can be found on the Configuration page in Lutris, eg. lutris:the-battle-for-wesnoth`. That would be a great feature !

**Comment by Fr75s** [comment]
I can see now how this would be a good idea. I was unaware that Pegasus only scrapes a few assets from Lutris, so I can see how it would be better to use this tool to scrape more data.

The only thing I'm wondering is if I should scrape Lutris itself, or have an option when exporting to choose "Pegasus (Lutris Identifiers)", which would replace the actual file paths with the games' Lutris identifiers (`file: lutris:my-game` vs `file: path/to/my-game`). This would accomplish what you're asking for, allowing you to scrape any other service to get metadata for your Lutris games. No new scraping modules would need to be added, but you'd still benefit from extra assets for your Lutris games. I feel that if the tool were to scrape Lutris itself (adding it as another scraping module), it would run into the same issue of few assets.

Whichever option you choose, I can work it in after I finish adding ScreenScraper support to bigscraper-qt.

**Comment by FrenchGithubUser** [comment]
Scraping from lutris itself would be useless as pegasus already does that (and lutris only scrapes a banner and an icon). But the second idea you mentionned seems great !


Oct 8, 2022, 15:56 by ***@***.***:

**Comment by Fr75s** [comment]
I've implemented a "Pegasus (Lutris IDs)" option when exporting in 436bc9b; further improvements will come later. This successfully manages to get the Lutris ID for games, acting like so:
```
...
game: My Game
file: lutris:my-game
...
```
Please tell me if there's a single launch command that launches Lutris games using the Lutris IDs. Other than that, this feature is about done and should be included in the next update of bigscraper-qt.

**Comment by FrenchGithubUser** [comment]
Perfect ! There is no launch command to give.
I was also wondering if the program automatically finds the folder with lutris games or if we still have to give the games folder every time.


Oct 9, 2022, 22:21 by ***@***.***:
