### ISSUE TITLE
Suggestion : Keep launch command

### ISSUE THREAD

**Issue by FrenchGithubUser** [Fr75s/bigscraperqt#3]
If a system has already been scraped and a launch command has been added to the metadata file. New games are added and rescraped. When exporting the metadata file, the launch command is removed in the new file. It would be great to keep it in the new metadata file !

**Comment by Fr75s** [comment]
This issue should be fixed in 1601d5d. Launch commands are now preserved when re-exporting for a system.

Thank you for submitting this issue.
